### ISSUE TITLE
About test results

### ISSUE THREAD

**Issue by Young-Zzz** [greatlog/DAN#30]
Hi,DAN is very cool and thanks you for releasing the code!
When I run the test.py in  DANv1,I didn't run the generate_mod_blur_LR_bic.py and create_lmdb.py,just set the LR and HR images in options/setting1/xx.yml,such as in setting1_x2.yml:
```
 test1:
    name: Set5
    mode: LQGT
    dataroot_GT: /datasets/Set5/LR/x2
    dataroot_LQ: /datasets/Set5/HR/x2
```
But the result of PSNR/SSIM is 35.59dB/0.938,is lower than the results in your paper."37.34/0.9526"
May I ask is that  the different setting of the .yml file contribute to the non-ideal results？
